import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href="/"> Home</Link>
          <Link href="/events"> Events</Link>
          <Link href="/about-us"> About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <Link href="">
          <h2> Events in London</h2>
          <p>
            cosmopolitan cities in the world, made up of a multi-ethnic
            population. The applied name in Chinese characters is written
            &quot;Lun Dun,&quot; and the city has long been in contact with
            Japan. London has more than 300 museums and art galleries of all
            sizes combined. There are many universities, technical schools and
            language schools, and international students from all over the world
            come to study here.
          </p>
        </Link>
        <Link href="">
          <h2> Events in Francisco</h2>
          <p>
            cosmopolitan cities in the world, made up of a multi-ethnic
            population. The applied name in Chinese characters is written
            &quot;Lun Dun,&quot; and the city has long been in contact with
            Japan. London has more than 300 museums and art galleries of all
            sizes combined. There are many universities, technical schools and
            language schools, and international students from all over the world
            come to study here.
          </p>
        </Link>
        <Link href="">
          <h2> Events in Barcelona</h2>
          <p>
            cosmopolitan cities in the world, made up of a multi-ethnic
            population. The applied name in Chinese characters is written
            &quot;Lun Dun,&quot; and the city has long been in contact with
            Japan. London has more than 300 museums and art galleries of all
            sizes combined. There are many universities, technical schools and
            language schools, and international students from all over the world
            come to study here.
          </p>
        </Link>
      </main>
      <footer>
        {/* 著作権表記追加 */}
        <p> © 2022 Time to Code - Project Next.js Tutorial</p>
      </footer>
    </>
  );
}
